import { queryNumber } from "@/lib/data";
import AdminForm from "@/components/admin-form";
import { createGame, saveGameResult, saveGameTime, deleteGame } from "../actions";
import { requireAdmin } from "@/lib/admin";

export default async function AdminGames({ searchParams }: { searchParams: Promise<{year?:string;week?:string}> }) {
  const supabase = await requireAdmin();
  const q=await searchParams;
  const {data:seasons,error:seasonsError}=await supabase.from("season").select("year,is_current").order("year",{ascending:false});
  const year=queryNumber(q.year,1920,9999) ?? seasons?.find(row=>row.is_current)?.year ?? seasons?.[0]?.year ?? new Date().getFullYear();
  const {data:weeks,error:weeksError}=await supabase.from("week").select("week,is_current").eq("year",year).order("week");
  const week=queryNumber(q.week,1,22) ?? weeks?.find(row=>row.is_current)?.week ?? weeks?.[0]?.week ?? 1;
  const [{ data: teams, error: teamsError }, { data: games, error: gamesError }] = await Promise.all([
    supabase.from("team").select("team_id,team_name").in("team_id", Array.from({ length: 32 }, (_, index) => index + 1)).order("team_id"),
    supabase.from("game").select("game_id,year,week,away_team_id,home_team_id,win_team_id,game_date_time").eq("year",year).eq("week",week).order("game_id"),
  ]);
  if (seasonsError || weeksError || teamsError || gamesError) return <p role="alert">Unable to load administration data. Refresh to retry.</p>;
  const names = new Map((teams ?? []).map((team) => [team.team_id, team.team_name]));
  return <div className="form-stack"><form method="get" className="toolbar"><label>Season <select name="year" defaultValue={year}>{(seasons ?? []).map(row=><option key={row.year} value={row.year}>{row.year}</option>)}</select></label><label>Week <select name="week" defaultValue={week}>{(weeks ?? []).map(row=><option key={row.week} value={row.week}>{row.week}</option>)}</select></label><button className="button secondary">View week</button></form>
    <section className="card"><h2>Add game</h2><AdminForm action={createGame} resetOnSuccess className="compact-form"><label>Season <input required name="year" type="number" defaultValue={year} /></label><label>Week <input required name="week" type="number" defaultValue={week} min="1" max="22" /></label><label>Away <select name="away_team_id">{(teams ?? []).map((team) => <option key={team.team_id} value={team.team_id}>{team.team_name}</option>)}</select></label><label>Home <select name="home_team_id">{(teams ?? []).map((team) => <option key={team.team_id} value={team.team_id}>{team.team_name}</option>)}</select></label><label>Kickoff with time zone <input name="game_date_time" placeholder="2026-09-13T14:25-06:00" /></label><button className="button">Add game</button></AdminForm></section>
    <section className="card"><h2>Results · {year} W{week}</h2>{!games?.length && <p>No games for this week yet.</p>}<div className="form-stack">{(games ?? []).map((game) => <AdminForm action={saveGameResult} className="result-form" key={game.game_id}><input type="hidden" name="game_id" value={game.game_id} /><span>{game.year} W{game.week}: {names.get(game.away_team_id)} at {names.get(game.home_team_id)}</span><label>Result <select name="win_team_id" defaultValue={game.win_team_id}><option value="34">TBD / open</option><option value="33">Tie</option><option value={game.away_team_id}>{names.get(game.away_team_id)}</option><option value={game.home_team_id}>{names.get(game.home_team_id)}</option></select></label><label className="check-label"><input name="confirm_result" type="checkbox" /> Confirm result change (TBD reopens picks)</label><button className="button secondary">Save result</button></AdminForm>)}</div></section>
    <section className="card"><h2>Game maintenance</h2><p>Use an explicit time-zone offset for kickoff. Games can only be removed before picks exist.</p><div className="form-stack">{(games ?? []).map(game=><div key={game.game_id}><h3>{game.year} W{game.week}: {names.get(game.away_team_id)} at {names.get(game.home_team_id)}</h3><AdminForm action={saveGameTime} className="compact-form"><input type="hidden" name="game_id" value={game.game_id} /><label>Kickoff with time zone <input name="game_date_time" defaultValue={game.game_date_time ? new Date(game.game_date_time).toISOString().replace(".000Z","Z") : ""} placeholder="2026-09-13T14:25-06:00" /></label><button className="button secondary">Save kickoff</button></AdminForm><AdminForm action={deleteGame} className="compact-form"><input type="hidden" name="game_id" value={game.game_id} /><label className="check-label"><input type="checkbox" name="confirm_delete" required /> Remove this game if no picks exist</label><button className="button secondary">Remove game</button></AdminForm></div>)}</div></section>
  </div>;
}
