-- Historical IDs remain explicit/importable. No family accounts are required.
alter default privileges for role postgres in schema public revoke all on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public revoke all on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public revoke all on functions from anon, authenticated, service_role;
-- PostgreSQL grants function EXECUTE to PUBLIC globally, independently of schema defaults.
alter default privileges for role postgres revoke execute on functions from public;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.entry (
  entry_id bigint generated by default as identity primary key check (entry_id > 0),
  name_first text not null check (btrim(name_first) <> ''),
  name_last text not null default '',
  active boolean not null default true
);
create table private.entry_contact (
  entry_id bigint primary key references public.entry on delete cascade,
  email text not null check (email = btrim(email) and email ~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
);
create table public.team (
  team_id smallint primary key check (team_id between 1 and 34),
  team_name text not null unique
);
insert into public.team (team_id, team_name) values
  (1,'Cardinals'),(2,'Falcons'),(3,'Ravens'),(4,'Bills'),(5,'Panthers'),(6,'Bears'),
  (7,'Bengals'),(8,'Browns'),(9,'Cowboys'),(10,'Broncos'),(11,'Lions'),(12,'Packers'),
  (13,'Texans'),(14,'Colts'),(15,'Jaguars'),(16,'Chiefs'),(17,'Dolphins'),(18,'Vikings'),
  (19,'Patriots'),(20,'Saints'),(21,'Giants'),(22,'Jets'),(23,'Raiders'),(24,'Eagles'),
  (25,'Steelers'),(26,'Chargers'),(27,'49ers'),(28,'Seahawks'),(29,'Rams'),
  (30,'Buccaneers'),(31,'Titans'),(32,'Commanders'),(33,'Tie'),(34,'TBD');

create table public.season (
  year integer primary key check (year between 1920 and 9999),
  active boolean not null default true,
  is_current boolean not null default false,
  check (not is_current or active)
);
create unique index season_one_current on public.season (is_current) where is_current;
create table public.week (
  year integer not null references public.season,
  week integer not null check (week between 1 and 22),
  published boolean not null default false,
  is_current boolean not null default false,
  primary key (year, week),
  check (not is_current or published)
);
create unique index week_one_current_per_season on public.week (year) where is_current;

create table public.game (
  game_id bigint generated by default as identity primary key check (game_id > 0),
  year integer not null,
  week integer not null,
  away_team_id smallint not null references public.team check (away_team_id between 1 and 32),
  home_team_id smallint not null references public.team check (home_team_id between 1 and 32),
  win_team_id smallint not null default 34 references public.team,
  game_date_time timestamptz,
  foreign key (year, week) references public.week,
  check (away_team_id <> home_team_id),
  check (win_team_id in (33, 34) or win_team_id in (away_team_id, home_team_id)),
  unique (year, week, away_team_id, home_team_id)
);
create table public.pick (
  pick_id bigint generated by default as identity primary key check (pick_id > 0),
  entry_id bigint not null references public.entry,
  game_id bigint not null references public.game,
  team_id smallint not null references public.team check (team_id between 1 and 32),
  updated_at timestamptz not null default now(),
  unique (entry_id, game_id)
);
create index pick_game_idx on public.pick (game_id);
create index pick_team_idx on public.pick (team_id);
create index game_away_idx on public.game (away_team_id);
create index game_home_idx on public.game (home_team_id);
create index game_winner_idx on public.game (win_team_id);

comment on column public.game.win_team_id is '34 = open; 33 = tie/locked; matchup winner = locked. Kickoff does not lock picks.';
comment on table public.entry is 'Honor-system participant identity; not an authentication identity. Email is stored separately in private.entry_contact.';
