create table public.theme (
  theme_id bigint generated by default as identity primary key,
  theme_name text not null unique check (btrim(theme_name) <> ''),
  description text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  is_default boolean not null default false,
  check (not is_default or active)
);
create unique index theme_one_default on public.theme (is_default) where is_default;
insert into public.theme (theme_name, is_default) values ('Default', true);
create table public.team_theme_image (
  team_theme_image_id bigint generated by default as identity primary key,
  team_id smallint not null references public.team check (team_id between 1 and 32),
  theme_id bigint not null references public.theme,
  image_url text not null check (image_url ~ '^https://'),
  thumbnail_url text check (thumbnail_url ~ '^https://'),
  active boolean not null default true,
  sort_order integer not null default 0,
  unique (team_id, theme_id)
);
create index team_theme_image_theme_idx on public.team_theme_image (theme_id);
create table public.weekly_submission (
  entry_id bigint not null references public.entry,
  year integer not null,
  week integer not null,
  theme_id bigint not null references public.theme,
  submitted_at timestamptz not null default now(),
  revision integer not null default 1 check (revision > 0),
  primary key (entry_id, year, week),
  foreign key (year, week) references public.week
);
create index weekly_submission_latest_idx on public.weekly_submission (entry_id, submitted_at desc);
create index weekly_submission_week_idx on public.weekly_submission (year, week);
create index weekly_submission_theme_idx on public.weekly_submission (theme_id);

create table private.admin_user (
  user_id uuid primary key references auth.users on delete cascade
);
create function private.is_admin() returns boolean
language sql stable security definer set search_path = '' as $$
  select exists (select 1 from private.admin_user where user_id = auth.uid());
$$;
revoke all on function private.is_admin() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_admin() to authenticated;

create table private.admin_audit (
  audit_id bigint generated always as identity primary key,
  actor_id uuid not null,
  action text not null,
  record_id bigint not null,
  reason text not null check (btrim(reason) <> ''),
  before_value jsonb,
  after_value jsonb,
  occurred_at timestamptz not null default now()
);
create table public.league_settings (
  singleton boolean primary key default true check (singleton),
  league_message text not null default '',
  rules text not null default ''
);
insert into public.league_settings default values;
create table private.email_settings (
  singleton boolean primary key default true check (singleton),
  enabled boolean not null default false,
  sender_address text,
  reply_to_address text
);
insert into private.email_settings default values;
-- Immutable submission snapshot; never used to calculate scores or theme preferences.
-- Provider keys belong in server environment configuration, not this table.
create table private.email_outbox (
  request_id uuid primary key,
  entry_id bigint not null references public.entry,
  year integer not null,
  week integer not null,
  request_payload jsonb not null,
  confirmation jsonb not null,
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  foreign key (entry_id, year, week) references public.weekly_submission
);
create index email_outbox_pending_idx on private.email_outbox (created_at) where sent_at is null;

-- Serialize weekly game changes with submissions (including newly added games).
create function private.guard_game() returns trigger
language plpgsql set search_path = '' as $$
begin
  if TG_OP = 'DELETE' then
    perform 1 from public.week where year = old.year and week = old.week for update;
    return old;
  end if;
  perform 1 from public.week where year = new.year and week = new.week for update;
  if TG_OP = 'UPDATE' then
    if (old.year, old.week, old.away_team_id, old.home_team_id) is distinct from
       (new.year, new.week, new.away_team_id, new.home_team_id)
       and exists (select 1 from public.pick where game_id = old.game_id) then
      raise exception 'Cannot change the matchup or week after picks exist';
    end if;
    if old.win_team_id <> new.win_team_id and private.is_admin() then
      insert into private.admin_audit (actor_id, action, record_id, reason, before_value, after_value)
      values (auth.uid(), 'game_result', old.game_id, 'Administrator result change', to_jsonb(old), to_jsonb(new));
    end if;
  end if;
  return new;
end;
$$;
-- Definer is needed for the audit insert and hidden-week reads under admin RLS.
alter function private.guard_game() security definer;
create trigger guard_game before insert or update or delete on public.game
for each row execute function private.guard_game();

-- Even privileged imports must select a matchup team. The row lock is shared
-- with result updates; an admin correction may intentionally change a locked pick.
create function private.guard_pick() returns trigger
language plpgsql security definer set search_path = '' as $$
declare g public.game;
begin
  select * into g from public.game where game_id = new.game_id for update;
  if not found or new.team_id not in (g.away_team_id, g.home_team_id) then
    raise exception 'Pick must select one of the matchup teams';
  end if;
  new.updated_at := clock_timestamp();
  return new;
end;
$$;
create trigger guard_pick before insert or update on public.pick
for each row execute function private.guard_pick();

create function public.submit_weekly_picks(
  p_entry_id bigint, p_year integer, p_week integer, p_theme_id bigint,
  p_request_id uuid, p_picks jsonb
) returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_payload jsonb;
  v_existing private.email_outbox;
  v_result jsonb;
  v_revision integer;
begin
  if p_request_id is null or p_picks is null or jsonb_typeof(p_picks) <> 'array' then
    raise exception 'A request ID and picks array are required';
  end if;
  v_payload := jsonb_build_object('entry_id', p_entry_id, 'year', p_year, 'week', p_week,
    'theme_id', p_theme_id, 'picks', p_picks);
  -- A request ID is an idempotency key, not an identity credential.
  perform pg_advisory_xact_lock(hashtextextended(p_request_id::text, 0));
  select * into v_existing from private.email_outbox where request_id = p_request_id;
  if found then
    if v_existing.request_payload <> v_payload then
      raise exception 'Request ID was already used for a different submission';
    end if;
    return v_existing.confirmation;
  end if;
  perform 1 from public.entry where entry_id = p_entry_id and active for share;
  if not found then raise exception 'Player is not active'; end if;
  perform 1 from public.season where year = p_year and active for share;
  if not found then raise exception 'Season is not active'; end if;
  perform 1 from public.week where year = p_year and week = p_week and published for update;
  if not found then raise exception 'Week is not published'; end if;
  perform 1 from public.theme where theme_id = p_theme_id and active for share;
  if not found then raise exception 'Theme is not active'; end if;
  if not exists (select 1 from private.entry_contact where entry_id = p_entry_id) then
    raise exception 'Player needs an email address configured by the administrator';
  end if;
  -- Lock results before validating or writing picks, in a consistent order.
  perform 1 from public.game where year = p_year and week = p_week order by game_id for update;
  if not exists (select 1 from public.game where year = p_year and week = p_week) then
    raise exception 'Week has no games';
  end if;
  if exists (select 1 from jsonb_array_elements(p_picks) p
    where jsonb_typeof(p) <> 'object' or p->>'game_id' is null or p->>'team_id' is null) then
    raise exception 'Each pick requires game_id and team_id';
  end if;
  if exists (select 1 from jsonb_to_recordset(p_picks) as p(game_id bigint, team_id smallint)
    group by game_id having count(*) > 1) then
    raise exception 'Duplicate game in submission';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(p_picks) as p(game_id bigint, team_id smallint)
    left join public.game g on g.game_id = p.game_id
    where g.game_id is null or g.year <> p_year or g.week <> p_week
      or p.team_id not in (g.away_team_id, g.home_team_id)
  ) then raise exception 'Invalid game or selected team'; end if;
  if exists (
    select 1 from public.game g where g.year = p_year and g.week = p_week and g.win_team_id = 34
    and not exists (select 1 from jsonb_to_recordset(p_picks) as p(game_id bigint, team_id smallint)
      where p.game_id = g.game_id)
  ) then raise exception 'Select a team for every open game'; end if;
  -- Locked games may be omitted or echoed unchanged, never added/changed.
  if exists (
    select 1 from jsonb_to_recordset(p_picks) as p(game_id bigint, team_id smallint)
    join public.game g on g.game_id = p.game_id
    left join public.pick existing on existing.entry_id = p_entry_id and existing.game_id = g.game_id
    where g.win_team_id <> 34 and (existing.pick_id is null or existing.team_id <> p.team_id)
  ) then raise exception 'Game is locked'; end if;
  insert into public.pick (entry_id, game_id, team_id)
    select p_entry_id, p.game_id, p.team_id
    from jsonb_to_recordset(p_picks) as p(game_id bigint, team_id smallint)
    join public.game g on g.game_id = p.game_id where g.win_team_id = 34
    on conflict (entry_id, game_id) do update set team_id = excluded.team_id;
  insert into public.weekly_submission (entry_id, year, week, theme_id, submitted_at)
    values (p_entry_id, p_year, p_week, p_theme_id, clock_timestamp())
    on conflict (entry_id, year, week) do update set theme_id = excluded.theme_id,
      submitted_at = excluded.submitted_at, revision = public.weekly_submission.revision + 1
    returning revision into v_revision;
  v_result := jsonb_build_object('entry_id', p_entry_id, 'year', p_year, 'week', p_week,
    'theme_id', p_theme_id, 'revision', v_revision, 'email_status', 'queued',
    'picks', (select coalesce(jsonb_agg(jsonb_build_object('game_id', p.game_id, 'team_id', p.team_id)
      order by p.game_id), '[]'::jsonb) from public.pick p join public.game g using (game_id)
      where p.entry_id = p_entry_id and g.year = p_year and g.week = p_week));
  insert into private.email_outbox (request_id, entry_id, year, week, request_payload, confirmation)
    values (p_request_id, p_entry_id, p_year, p_week, v_payload, v_result);
  return v_result;
end;
$$;

create function public.admin_correct_pick(p_entry_id bigint, p_game_id bigint, p_team_id smallint, p_reason text)
returns void language plpgsql security definer set search_path = '' as $$
declare v_before jsonb; v_after jsonb;
begin
  if not private.is_admin() then raise exception 'Administrator required'; end if;
  if p_reason is null or btrim(p_reason) = '' then raise exception 'Correction reason required'; end if;
  perform 1 from public.game where game_id = p_game_id for update;
  select to_jsonb(p) into v_before from public.pick p where entry_id = p_entry_id and game_id = p_game_id;
  insert into public.pick (entry_id, game_id, team_id) values (p_entry_id, p_game_id, p_team_id)
    on conflict (entry_id, game_id) do update set team_id = excluded.team_id
    returning to_jsonb(pick.*) into v_after;
  insert into private.admin_audit (actor_id, action, record_id, reason, before_value, after_value)
    values (auth.uid(), 'pick_correction', p_game_id, p_reason, v_before, v_after);
end;
$$;
